language: go
go:
  - 1.6
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/Masterminds/glide
  - glide up
  - pwd
  - ls -l
install:
  - ls
  - du -a vendor
script:
  - (cd bb && go build . && ./bb)
  - which go
  - (cd scripts && go build ramfs.go)
  - (cd cmds && go test ./...)
  - echo "Did it blend"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then ghr --username u-root --token $GITHUB_TOKEN --replace --prerelease --debug `git describe --always`  dist/; fi
