ignored = ["github.com/u-root/u-root/bb*"]

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netlink"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "master"
  name = "pack.ag/tftp"

[[constraint]]
  branch = "master"
  name = "github.com/rck/unit"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-tpm"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/beevik/ntp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/gliderlabs/ssh"
  revision = "cbabf541443203944eeedf87d8bb92e2924170b5"

[[constraint]]
  name = "github.com/9elements/converged-security-suite"
  version = "2.0.0"
