ignored = ["github.com/u-root/u-root/bb*"]

[[constraint]]
  branch = "master"
  name = "github.com/vishvananda/netlink"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/sys"

[[constraint]]
  branch = "master"
  name = "golang.org/x/tools"

[[constraint]]
  branch = "master"
  name = "github.com/rck/unit"

[[constraint]]
  name = "github.com/google/go-tpm"
  revision = "aab8d06b4c87613d2d8f0fcef5d2c9ebed0b6e2e"

[[constraint]]
  branch = "master"
  name = "github.com/9elements/tpmtool"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/beevik/ntp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/gliderlabs/ssh"
  revision = "cbabf541443203944eeedf87d8bb92e2924170b5"

[[constraint]]
  name = "github.com/awnumar/memguard"
  version = "0.21.0"
