name: "Auto Assign"
on:
  - pull_request

jobs:
  assign_reviewer:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: shufo/auto-assign-reviewer-by-files@v1.1.2
        with:
          config: "MAINTAINERS"
          token: ${{ secrets.GITHUB_TOKEN }}
